[tool.poetry]
name = "rctab-controller-function"
version = "0.1.0" # Do not change
description = "Function app to control (enable/disable) Azure subscriptions"
authors = []

[tool.poetry.dependencies]
python = "^3.10"
pydantic = {extras = ["dotenv"], version = "^1.8.2"}
azure-functions = "^1.7.2"
azure-mgmt-subscription = "^1.0.0"
azure-identity = "^1.6.1"
PyJWT = {extras = ["crypto"], version = "^2.1.0"}
requests = "^2.26.0"
azure-mgmt-resource = "^20.0.0"
opencensus-ext-azure = "^1.1.7"


[tool.poetry.group.dev.dependencies]
flake8 = "^3.9.2"
black = "^21.8b0"
coverage = "^5.5"
pulumi = "^3.12.0"
pulumi-azure = "^4.18.0"
pytest = "^6.2.5"
pylint = "^2.17.4"
pylint-absolute-imports = "^1.0.1"
isort = "^5.12.0"
