# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii", "--no-sort-keys"]
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.8
    hooks:
      - id: pymarkdown
        name: PyMarkdown
        entry: pymarkdown --config .pymarkdown.json
        exclude: .github/
  - repo: 'https://github.com/gitleaks/gitleaks'
    rev: v8.16.1
    hooks:
      - id: gitleaks
  - repo: 'https://github.com/PyCQA/pydocstyle'
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ["--convention=google"]
