---

name: All Usage checks and tests

on:
  push:
    branches-ignore:
      - main
    paths:
      - "usage_function/**"
      - ".github/workflows/**"

jobs:

  usage-job:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Bootstrap poetry
        shell: bash
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Set up cache
        uses: actions/cache@v6
        id: cache
        with:
          path: usage_function/.venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('usage_function/poetry.lock') }}

      - name: Check poetry.lock consistency
        shell: bash
        run: |
          poetry check --lock
        working-directory: usage_function

      - name: Install dependencies
        shell: bash
        run: |
          poetry install
        working-directory: usage_function

      - name: Run tests
        shell: bash
        run: |
          poetry run ./run_tests.sh
        working-directory: usage_function
