---

name: All status checks and tests

on:
  push:
    branches-ignore:
      - main
    paths:
      - "status_function/**"
      - ".github/workflows/**"

jobs:

  status-job:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Bootstrap poetry
        shell: bash
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Configure poetry
        shell: bash
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Set up cache
        uses: actions/cache@v4
        id: cache
        with:
          path: status_function/.venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('status_function/poetry.lock') }}

      - name: Check poetry.lock consistency
        shell: bash
        run: |
          pwd
          cd status_function
          poetry check --lock

      - name: Install dependencies
        shell: bash
        run: |
          pwd
          cd status_function
          python -m poetry install

      - name: Run tests
        shell: bash
        run: |
          pwd
          cd status_function
          source .venv/bin/activate
          ./run_tests.sh
