---

name: Pre-commit checks

on:
  push:
    branches-ignore:
      - main

jobs:

  pre-commit-job:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
