# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Check images can be built

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    # Use a matrix to run for "controller", "status", and "usage" functions
    # https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      matrix:
        function: [controller, usage, status]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Bootstrap poetry
        shell: bash
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Build function
        run: |
          poetry install
          poetry export -f requirements.txt --output requirements.txt --only main --without-hashes
          docker build .
        working-directory: ${{ matrix.function }}_function
